### ISSUE TITLE
Change YAML multiline string style for comments

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort-config#120]
I just [realized](https://yaml-multiline.info/) that the `|` we're currently using for multiline curation comments adds a trailing newline. This becomes visible as `\n` as part of the resolved configuration in analyzer results:

```
  - provider:
      id: "DefaultDir"
    curations:
    - id: "Maven:com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"
      curations:
        comment: "This library is empty as its version string suggests.\n"
        is_metadata_only: true
```

This is not so nice. Thus I'm proposing to change comments to use `>-` instead, which strip the final newline and also folds lines.

Opinions @fviernau, @mnonnenmacher?
